### ISSUE TITLE
无法在项目中使用，提示找不到一些 dart 文件

### ISSUE THREAD

**Issue by GvcZhang** [XianyuTech/aspectd#112]
@kangwang1988 你好，帮忙看一下这个问题，我新创建一个 flutter 项目测试是没问题，但是一使用我们的实际项目就会报如下的错误，尝试过删除 `.packages`和`pubspec.lock`文件，但还是存在同样的问题：

```
Error: Could not resolve the package 'flutter_screenutil' in 'package:flutter_screenutil/flutter_screenutil.dart'.
../my_flutter_project/lib/pages/home.dart:19:8: Error: Not found: 'package:flutter_screenutil/flutter_screenutil.dart'
import 'package:flutter_screenutil/flutter_screenutil.dart';
       ^
Error: Could not resolve the package 'sqflite' in 'package:sqflite/sqflite.dart'.
Error: Could not resolve the package 'location' in 'package:location/location.dart'.
../my_flutter_project/lib/utils/utils.dart:8:8: Error: Not found: 'package:flutter_screenutil/flutter_screenutil.dart'
import 'package:flutter_screenutil/flutter_screenutil.dart';
       ^
Error: Could not resolve the package 'vibrate' in 'package:vibrate/vibrate.dart'.
../my_flutter_project/lib/db/data_migration.dart:6:8: Error: Not found: 'package:sqflite/sqflite.dart'
import 'package:sqflite/sqflite.dart';
       ^
../my_flutter_project/lib/db/program.dart:5:8: Error: Not found: 'package:sqflite/sqflite.dart'
import 'package:sqflite/sqflite.dart';
       ^
../my_flutter_project/lib/db/screen.dart:5:8: Error: Not found: 'package:sqflite/sqflite.dart'
import 'package:sqflite/sqflite.dart';
       ^
../my_flutter_project/lib/db/node_service.dart:6:8: Error: Not found: 'package:sqflite/sqflite.dart'
import 'package:sqflite/sqflite.dart';
       ^
../my_flutter_project/lib/repository/common.dart:3:8: Error: Not found: 'package:location/location.dart'
import 'package:location/location.dart';
       ^
../my_flutter_project/lib/bloc/screen/user_info/main.dart:5:8: Error: Not found: 'package:location/location.dart'
import 'package:location/location.dart';
       ^
../my_flutter_project/lib/widgets/program/drage.dart:7:8: Error: Not found: 'package:vibrate/vibrate.dart'
import 'package:vibrate/vibrate.dart';
       ^
Error: Could not resolve the package 'percent_indicator' in 'package:percent_indicator/percent_indicator.dart'.
../my_flutter_project/lib/widgets/common/circular_percent_indicator.dart:3:8: Error: Not found: 'package:percent_indicator/percent_indicator.dart'
import 'package:percent_indicator/percent_indicator.dart';
       ^
../my_flutter_project/lib/pages/home.dart:508:9: Error: The getter 'ScreenUtil' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:my_flutter_project/pages/home.dart' ('../my_flutter_project/lib/pages/home.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScreenUtil'.
        ScreenUtil.init(context, width: 750, height: 1334);
        ^^^^^^^^^^
../my_flutter_project/lib/pages/home.dart:510:9: Error: The getter 'ScreenUtil' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:my_flutter_project/pages/home.dart' ('../my_flutter_project/lib/pages/home.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScreenUtil'.
        ScreenUtil.init(context, width: 1334, height: 750);
        ^^^^^^^^^^
../my_flutter_project/lib/pages/home.dart:552:13: Error: The getter 'ScreenUtil' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:my_flutter_project/pages/home.dart' ('../my_flutter_project/lib/pages/home.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScreenUtil'.
            ScreenUtil.init(context, width: 750, height: 1334);
            ^^^^^^^^^^
../my_flutter_project/lib/pages/home.dart:554:13: Error: The getter 'ScreenUtil' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:my_flutter_project/pages/home.dart' ('../my_flutter_project/lib/pages/home.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScreenUtil'.
            ScreenUtil.init(context, width: 1334, height: 750);
            ^^^^^^^^^^
../my_flutter_project/lib/repository/common.dart:30:5: Error: 'Location' isn't a type.
    Location location = new Location();
    ^^^^^^^^
../my_flutter_project/lib/repository/common.dart:30:29: Error: Method not found: 'Location'.
    Location location = new Location();
                            ^^^^^^^^
../my_flutter_project/lib/repository/common.dart:33:5: Error: 'PermissionStatus' isn't a type.
    PermissionStatus _permissionGranted;
    ^^^^^^^^^^^^^^^^
../my_flutter_project/lib/repository/common.dart:44:31: Error: Getter not found: 'PermissionStatus'.
    if (_permissionGranted == PermissionStatus.DENIED) {
                              ^^^^^^^^^^^^^^^^
../my_flutter_project/lib/repository/common.dart:47:33: Error: Getter not found: 'PermissionStatus'.
      if (_permissionGranted != PermissionStatus.GRANTED) {
                                ^^^^^^^^^^^^^^^^
../my_flutter_project/lib/repository/common.dart:66:42: Error: 'LocationData' isn't a type.
    location.onLocationChanged().listen((LocationData currentLocation) {
                                         ^^^^^^^^^^^^
../my_flutter_project/lib/utils/utils.dart:178:16: Error: Method not found: 'ScreenUtil'.
      result = ScreenUtil().setSp(size.toDouble());
               ^^^^^^^^^^
../my_flutter_project/lib/utils/utils.dart:191:16: Error: Method not found: 'ScreenUtil'.
      result = ScreenUtil().setWidth(size.toDouble());
               ^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:22:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:56:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:88:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:350:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:386:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:432:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:467:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:506:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:535:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:585:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:605:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:625:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:658:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:679:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:696:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:714:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:735:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:755:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/db/program.dart:774:22: Error: Method not found: 'openDatabase'.
      var db = await openDatabase(dbPath);
                     ^^^^^^^^^^^^
../my_flutter_project/lib/widgets/program/drage.dart:195:39: Error: The getter 'FeedbackType' isn't defined for the class '_SortableGridViewState<T>'.
 - '_SortableGridViewState' is from 'package:my_flutter_project/widgets/program/drage.dart' ('../my_flutter_project/lib/widgets/program/drage.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FeedbackType'.
                        var _impact = FeedbackType.impact;
                                      ^^^^^^^^^^^^
../my_flutter_project/lib/widgets/program/drage.dart:196:25: Error: The getter 'Vibrate' isn't defined for the class '_SortableGridViewState<T>'.
 - '_SortableGridViewState' is from 'package:my_flutter_project/widgets/program/drage.dart' ('../my_flutter_project/lib/widgets/program/drage.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Vibrate'.
                        Vibrate.feedback(_impact);
                        ^^^^^^^
../my_flutter_project/lib/db/screen.dart:19:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/screen.dart:77:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/screen.dart:115:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/screen.dart:166:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/screen.dart:218:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/node_service.dart:24:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/db/node_service.dart:78:24: Error: Method not found: 'openDatabase'.
        var db = await openDatabase(dbPath);
                       ^^^^^^^^^^^^
../my_flutter_project/lib/widgets/common/circular_percent_indicator.dart:22:12: Error: The method 'CircularPercentIndicator' isn't defined for the class '_CircularPercentIndicatorPicker'.
 - '_CircularPercentIndicatorPicker' is from 'package:my_flutter_project/widgets/common/circular_percent_indicator.dart' ('../my_flutter_project/lib/widgets/common/circular_percent_indicator.dart').
Try correcting the name to the name of an existing method, or defining a method named 'CircularPercentIndicator'.
    return CircularPercentIndicator(
           ^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_screenutil%2Fflutter_screenutil.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:657:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:825:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (file:///Users/zw/Project/flutter_aspectd/lib/src/flutter_frontend_server/server.dart:52:22)
#5      starter (file:///Users//Project/flutter_aspectd/lib/src/flutter_frontend_server/server.dart:191:27)
#6      main (file:///Users/zw/Project/flutter_aspectd/lib/src/flutter_frontend_server/starter.dart:13:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



FAILURE: Build failed with an exception.

* Where:
Script '/Users/zw/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/zw/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       107.1s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by kangwang1988** [comment]
如果你确定你的依赖关系都有的话
可以试试flutter clean, pubspec.lock,.packages都删除看看。

**Comment by GvcZhang** [comment]
> 如果你确定你的依赖关系都有的话
> 可以试试flutter clean, pubspec.lock,.packages都删除看看。

不使用aspectd可以运行，flutter clean, pubspec.lock,.packages 这些都操作了以后还是不行

**Comment by GvcZhang** [comment]
@kangwang1988 与此问题 https://github.com/XianyuTech/aspectd/issues/42 出错是一样的，但是没有说原因和解决方式。
