### ISSUE TITLE
Flutter SDK 打了patch 后对没有aspectd 项目有影响

### ISSUE THREAD

**Issue by JsonYuu** [XianyuTech/aspectd#113]
19:29:39  > Task :flutter:compileFlutterBuildRelease
19:29:39  Unhandled exception:
19:29:39  Invalid argument(s): Missing canonical name for Reference to Widget.
19:29:39  #0      BinaryPrinter.writeNonNullReference (package:kernel/binary/ast_to_binary.dart:868:9)
19:29:39  #1      BinaryPrinter.visitSuperInitializer (package:kernel/binary/ast_to_binary.dart:1312:5)
19:29:39  #2      SuperInitializer.accept (package:kernel/ast.dart:2580:45)
19:29:39  #3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
19:29:39  #4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
19:29:39  #5      BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:1183:5)
19:29:39  #6      Constructor.accept (package:kernel/ast.dart:1976:40)
19:29:39  #7      BinaryPrinter.writeConstructorNode (package:kernel/binary/ast_to_binary.dart:438:10)
19:29:39  #8      BinaryPrinter.writeConstructorNodeList (package:kernel/binary/ast_to_binary.dart:337:7)
19:29:39  #9      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1141:5)
19:29:39  #10     Class.accept (package:kernel/ast.dart:1379:38)
19:29:39  #11     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:424:10)
19:29:39  #12     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:319:7)
19:29:39  #13     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:973:5)
19:29:39  #14     Library.accept (package:kernel/ast.dart:607:38)
19:29:39  #15     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:403:10)
19:29:39  #16     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:710:9)
19:29:39  #17     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:553:7)
19:29:39  #18     Timeline.timeSync (dart:developer/timeline.dart:163:22)
19:29:39  #19     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:536:14)
19:29:39  #20     FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:751:15)
19:29:39  #21     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:562:13)
19:29:39  <asynchronous suspension>
19:29:39  #22     _FlutterFrontendCompiler.compile (file:///home/flutter/flutter_linux_1.17.3-stable/.pub-cache/git/event_track-afa105d576be0588df429ecfc5a0d1bff3309fd9/lib/src/flutter_frontend_server/server.dart:58:22)
19:29:39  #23     starter (file:///home/flutter/flutter_linux_1.17.3-stable/.pub-cache/git/event_track-afa105d576be0588df429ecfc5a0d1bff3309fd9/lib/src/flutter_frontend_server/server.dart:197:27)
19:29:39  #24     main (file:///home/flutter/flutter_linux_1.17.3-stable/.pub-cache/git/event_track-afa105d576be0588df429ecfc5a0d1bff3309fd9/lib/src/flutter_frontend_server/starter.dart:13:30)
19:29:39  #25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
19:29:39  #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

打patch 过后的：
![image](https://user-images.githubusercontent.com/20380136/114805930-7798d900-9dd6-11eb-8c5d-dec8256be011.png)

@kangwang1988

**Comment by JsonYuu** [comment]
自身问题，已解决
