### ISSUE TITLE
编译问题，请大佬关注一下 （v1.17.5）

### ISSUE THREAD

**Issue by zhuangtao97** [XianyuTech/aspectd#117]
demo 运行没问题，也有成功hook，但是在demo里面随便引入一个三方库，再次编译就会报错。
如下：

Showing All Messages
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_gifimage%2Fflutter_gifimage.dart; message=StandardFileSystem only supports file:* and data:* URIs)

#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)

#1      asFileUri (package:vm/kernel_front_end.dart:567:37)

#2      writeDepfile (package:vm/kernel_front_end.dart:760:21)

<asynchronous suspension>

#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:539:15)

<asynchronous suspension>

#4      _FlutterFrontendCompiler.compile (file:///Users/zhuangtao/Documents/workspace/aspectd_v6/lib/src/flutter_frontend_server/server.dart:49:22)

#5      starter (file:///Users/zhuangtao/Documents/workspace/aspectd_v6/lib/src/flutter_frontend_server/server.dart:187:27)

#6      main (file:///Users/zhuangtao/Documents/workspace/aspectd_v6/lib/src/flutter_frontend_server/starter.dart:7:30)

#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)

#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

**Comment by zhuangtao97** [comment]
@kangwang1988 能帮忙看看吗
aspectd_impl 依赖本地aspectd  随便添加一个三方库，并且在代码中使用，就会报编译错误。
我就是在demo中直接引入一个三方库 编译就会有问题，麻烦帮忙看看。
aspectd_impl 依赖远程库就没问题。
