### ISSUE TITLE
1.22.2

### ISSUE THREAD

**Issue by zhuangtao97** [XianyuTech/aspectd#129]
1.22.2 demo 报以下错误
RangeError: RangeError: Value not in range: 68

```
#0      _StringBase.substring (dart:core-patch/string_patch.dart:390:7)
#1      AspectdHook.runBuildDillCommand (package:flutter_tools/src/aspectd.dart:180:10)
#2      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:199:27)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#4      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#24     _rootRun (dart:async/zone.dart:1190:13)
#25     _CustomZone.run (dart:async/zone.dart:1093:19)
#26     _runZoned (dart:async/zone.dart:1630:10)
#27     runZoned (dart:async/zone.dart:1550:10)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:281:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:223:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:230:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#35     _rootRun (dart:async/zone.dart:1190:13)
#36     _CustomZone.run (dart:async/zone.dart:1093:19)
#37     _runZoned (dart:async/zone.dart:1630:10)
#38     runZonedGuarded (dart:async/zone.dart:1618:12)
#39     runZoned (dart:async/zone.dart:1547:12)
#40     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#41     run.<anonymous closure> (package:flutter_tools/runner.dart)
#42     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#43     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#45     _rootRun (dart:async/zone.dart:1190:13)
#46     _CustomZone.run (dart:async/zone.dart:1093:19)
#47     _runZoned (dart:async/zone.dart:1630:10)
#48     runZoned (dart:async/zone.dart:1550:10)
#49     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#50     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#51     run (package:flutter_tools/runner.dart:46:10)
#52     main (package:flutter_tools/executable.dart:77:9)
#53     main (file:///Users/zhuangtao/Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#54     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by zhuangtao97** [comment]
@kangwang1988 @erjanmx  @soloxiao @fightcoder  能帮忙看看吗

我的Flutter版本 是1.22.2
